keys:
  - &padraic age1sartew6ntahhyg06p72rpy77xuyw0gh28zp76ynl3na3v73l7ufqjm5sd5
  - &Hydrogen age1arrfttxu8v0873mr22xmmdn0mjretm8n3kgtks55c3e5s2wd23kq6vmypx
  - &Oxygen
creation_rules:
  - path_regex: secrets/Hydrogen.yaml$
    key_groups:
    - age:
      - *padraic
      - *Hydrogen
  - path_regex: secrets/Oxygen.yaml$
    key_groups:
    - age:
      - *padraic
      - *Oxygen
