# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ "dm-snapshot" ];
      luks.devices = {
        enc-pv = {
          device = "/dev/disk/by-uuid/954da3dc-267e-4ad5-a15b-b5d3664f36f7";
          preLVM = true;
        };
      };
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a8a910e3-01db-4408-ac08-b9a6a27589eb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6CC1-3C40";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f7c2682b-908e-4ea4-b60a-1901673eef29"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware = {
    video.hidpi.enable = true;
    cpu.intel.updateMicrocode = true;
    enableAllFirmware = true;
  };

  services = {
    fwupd.enable = true;
    hardware.bolt.enable = true;
    thermald.enable = true;
  };
}
